---
- hosts: mediawiki
  become_user: "{{pac}}-{{user}}"
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: download patch
    become: yes
    get_url:
      url: https://releases.wikimedia.org/mediawiki/{{mediawiki_version}}/mediawiki-{{mediawiki_release}}.patch.gz
      dest: /home/pacs/{{pac}}/users/{{user}}

  - name: apply the patch
    become: yes
    shell: |
        gunzip -c ../mediawiki-{{mediawiki_release}}.patch | patch -p1 || exit -1
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/{{mediawiki_directory}}"

  - name: run the upgrade
    become: yes
    shell: |
        php update.php || exit -1
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/{{mediawiki_directory}}/maintenance"

  - name: drop the patch file
    become: yes
    file:
      path: /home/pacs/{{pac}}/users/{{user}}/mediawiki-{{mediawiki_release}}.patch.gz
      state: absent



